### ISSUE TITLE
Misspelling in the org

### ISSUE THREAD

**Issue by 3kh0** [NCSC-NL/OpenSSL-2022#140]
**Nationaal** Cyber Security Centrum (NCSC-NL)

![Screenshot 2022-11-02 15 11 11](https://user-images.githubusercontent.com/58097612/199580502-f372b7fe-9580-45f6-8c42-72d485e43ef4.png)

**Comment by rkokkelk** [comment]
Hi, thank you for your feedback. However, the organization name is correct, this is our Dutch organization name and thus not a typo of national.
