### ISSUE TITLE
Python cryptography lib

### ISSUE THREAD

**Issue by luislhl** [NCSC-NL/OpenSSL-2022#189]
Should the `cryptography` lib from Python be included in this list?

https://github.com/pyca/cryptography

They link OpenSSL at build time, so some versions of the lib could be carrying a vulnerable version of OpenSSL.

They've upgraded the lib already, their version 38.0.3 includes OpenSSL 3.0.7: https://github.com/pyca/cryptography/issues/7758

I think from 37.x.x to 38.0.2 all include a vulnerable OpenSSL

**Comment by fdellwing** [comment]
Is OpenSSL statically linked?
