### ISSUE TITLE
Harbor

### ISSUE THREAD

**Issue by captn3m0** [NCSC-NL/OpenSSL-2022#58]
Harbor docker images are vulnerable since it uses VMWare Photon 4.0 as base image.

Ref: https://github.com/goharbor/harbor/issues/17724

Deployments outside of Docker should not be impacted.

Vulnerable version range will most probably be `<=2.6.1`

**Comment by pbeij** [comment]
Hi, is it possible to do this via a Pull Request?
Please let me know if you need assistance.

**Comment by captn3m0** [comment]
Will file a PR in a bit.

**Comment by pbeij** [comment]
Thanks!
